### ISSUE TITLE
Crash after app appears from background

### ISSUE THREAD

**Issue by renshaw1** [pusher/chatkit-swift#101]
### What?

If I close the app (putting it on background, not shutting it down completely) after it has connected to Chatkit and subscribed to the user's rooms, and then re-open the app, the app _always_ crashes at exactly this location:

<img width="1187" alt="screen shot 2018-08-14 at 19 27 31" src="https://user-images.githubusercontent.com/25514354/44166444-b200c400-a0cb-11e8-9927-e5cac137304f.png">

I only call the _connect_ function once after the app starts (in _viewDidLoad_ of the first VC) and I don't call _disconnect_ when the app enters the background.

The crash doesn't occur when I only connect to the Chatkit without subscribing to any rooms. I subscribe to the rooms by looping through them once the connection to Chatkit has been established successfully. (Meaning I only call _subscribeToRoom_ once per room, when the app is started)

**Comment by halilyuce** [comment]
Did you solve it ? I have same problem here :/
