### ISSUE TITLE
createdAtDate on PCMessage causing crashes at times

### ISSUE THREAD

**Issue by steve228uk** [pusher/chatkit-swift#107]
### What?

`createdAtDate` on PCMessage force unwraps a date created from a string. There seems to be times when this has caused a crash for our users.

I've been unable to replicate the issue but I have but have seen crash reports coming in.

### Environment

* **PusherChatkit version:** 0.8.1
* **Xcode version:** 10.0
* **Swift version:** 4.1
* **Platform(s) running PusherChatkit:** iOS

----

CC @hamchapman

**Comment by hamchapman** [comment]
Do you have any more info on what the `createdAt` string value is for when the crash occurs?

**Comment by steve228uk** [comment]
Unfortunately not, @hamchapman 😟 I've only got the stack from the iOS crash report. It's coming from the `newMessage(message: PCMessage)` delegate method. When attempting to insert that into a collection view and read the value from `createdAtDate` the getter throws an error.

It's not something that we've been able to replicate it ourselves but have had multiple users and multiple crash reports from multiple devices through.

**Comment by lukabratos** [comment]
We might try and set the locale in the [DateFormatter](https://github.com/pusher/chatkit-swift/blob/master/Sources/PCMessage.swift#L12).

https://developer.apple.com/library/archive/qa/qa1480/_index.html

**Comment by hamchapman** [comment]
What's the workaround you've been using @steve228uk ?

**Comment by steve228uk** [comment]
@hamchapman I'm using a date formatter on the `createdAt` date but not force unwrapping. 

```swift
let dateFormatter = DateFormatter()
dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
let sentAt = dateFormatter.date(from: message.createdAt) ?? Date()
```

**Comment by clay-mindoula** [comment]
i just got this also:
````
self?.chatRooms[roomIndex].timeAgo = message.createdAtDate
```
Happened just the once so far, it was in the Sym alas so no crash report.

**Comment by hamchapman** [comment]
If you're able to, please try using the branch that forms #128 to see if that causes the crashes to go away

**Comment by clay-mindoula** [comment]
i'll take a look early next week, many thanks

**Comment by hamchapman** [comment]
The expected fix for this is now on master so if anyone has a chance to test that before I cut a new release then that would be much appreciated!
