### ISSUE TITLE
User Set in room returns nil

### ISSUE THREAD

**Issue by papanton** [pusher/chatkit-swift#111]
PCCurrentUser PCRooms have empty Sets for userIds. Is this the expected SDK behavior? 

`public internal(set) var userIDs: Set<String>`

Is nil on PCRoom init function. 

Xcode 10
Swift 4.2
ChatKit 1.0.0

**Comment by hamchapman** [comment]
The list of users that are members of a room will now only be populated once you've subscribed to the room that you're attempting to get the list of members for.
