### ISSUE TITLE
Background Crash and instanceLocator Problem

### ISSUE THREAD

**Issue by halilyuce** [pusher/chatkit-swift#117]
Hi, I have 2 important problem;

Messaging system working well but If I close the app (putting it on background, not shutting it down completely) after it has connected to Chatkit and subscribed to the user's rooms, and then re-open the app its crashing

<img width="911" alt="ekran resmi 2018-12-21 03 57 17" src="https://user-images.githubusercontent.com/29376592/50318801-89069a80-04d4-11e9-831f-7470da5ed8a8.png">

Second problem is I want to enable push notifications for messages but I thought I made everything was well and I`m sure my instanceLocator is true but I got this error;

Why instanceLocator string is optional I dont know, when I print(instanceLocator) it seems non-optional

<img width="1180" alt="ekran resmi 2018-12-21 03 59 29" src="https://user-images.githubusercontent.com/29376592/50318991-e2bb9480-04d5-11e9-875d-6f166cf814fd.png">

### Environment

* **PusherChatkit version: 1.2.2
* **Xcode version: 10.1
* **Swift version: 4.2
* **Platform(s) running PusherChatkit:iOS

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by halilyuce** [comment]
I did deleted PusherSwift pod and second problem was solved but background crash problem is still same.

**Comment by halilyuce** [comment]
> The push notifications issue should be fixed by the latest SDK release (1.2.3)
> 
> The crash when returning to the app from the background is more interesting though. We've had a report of something very similar before but I was never able to recreate it. Are you able to share your app with me so that I can try and recreate it and debug it? Feel free to email [hamilton@pusher.com](mailto:hamilton@pusher.com). Thanks!

thanks for reply, I sent my project to you via e-mail :)

**Comment by hamchapman** [comment]
Is this still an issue?

**Comment by halilyuce** [comment]
> Is this still an issue?

Nope, I solved it thanks :)
