### ISSUE TITLE
Subscribe Not Triggering when you call "subscribeToRoom" For Users In 50+ Chatrooms

### ISSUE THREAD

**Issue by jain-ruchi** [pusher/chatkit-swift#119]
### What?

Subscribe Not Triggering when you call "subscribeToRoom" For Users In 50+ Chatrooms. On launch we subscribe to all the rooms a user is in, however, the subscription is not taking place for a subset of the rooms or any new rooms that we attempt to subscribe to thereafter (say after creating a room).

Some theories that have been thrown around is that we are hitting the iOS limit on the number of SUBSCRIBE connections a session can have.

### Environment

* **PusherChatkit version: 1.2.3. **
* **Xcode version: 10.1 **
* **Swift version: 4.1**
* **Platform(s) running PusherChatkit: iOS 11.2 and up **

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by hamchapman** [comment]
This should be fixed now. It was a limit being imposed by our servers on the number of concurrent HTTP/2 streams per connection. This limit has been increased significantly now so you should be able to subscribe without issue 👍  

Let me know if it's still an issue!

**Comment by jain-ruchi** [comment]
@hamchapman Confirmed! Thanks for the support!
