### ISSUE TITLE
Edit Push Notification

### ISSUE THREAD

**Issue by halilyuce** [pusher/chatkit-swift#120]
I want to edit push notification title and content, is it possible ? Im creating rooms with random names at server side so it seems bad, I want to show user name as title and message as content.

How can do that ?

![img_0419](https://user-images.githubusercontent.com/29376592/50368002-786a2900-0595-11e9-83e5-cdc486c2f7eb.jpg)

### Environment

* **PusherChatkit version: 1.2.3
* **Xcode version: 10.1
* **Swift version: 4.2
* **Platform(s) running PusherChatkit: iOS

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by hamchapman** [comment]
This is something that we'll be adding support for in the future. Thanks for the feedback!

**Comment by halilyuce** [comment]
> This is something that we'll be adding support for in the future. Thanks for the feedback!

oh, thanks :) I hope it will be added before I release this app(in couple months) because it is so important :)

**Comment by jain-ruchi** [comment]
@halilyuce our team had a similar request -- our short term solution was to use empty strings for room creation which hides the title in push notifications

**Comment by halilyuce** [comment]
> @halilyuce our team had a similar request -- our short term solution was to use empty strings for room creation which hides the title in push notifications

thanks for suggestion @jain-ruchi , I will try it :)

**Comment by narsi-mindoula** [comment]
we also need this very badly. Unfortunately we are planning to go live with the app in a week or so and we can't do that without the support for push notifications. I think @jain-ruchi's solution solves it to some extent, but we also don't have real names for users. 

There was another talk of supporting web hooks for this feature. @hamchapman any other alternative to fix this problem if the web hooks is not implemented by then.

**Comment by vivangkumar** [comment]
I'm going to close this issues because it is already on our backlog and we'll be getting to it very soon! If you have further issues/ feature requests, please email support@pusher.com.
