### ISSUE TITLE
Local data store of recent messages?

### ISSUE THREAD

**Issue by Tom-Fox1** [pusher/chatkit-swift#125]
### What?

Is it currently possible/are there plans to add some sort of local data store of messages. I ideally want to be able to store the latest 30 messages so that the use can see them without an internet connection.

This doesn't currently seem to be possible (with the default library), is this the case?

CC @hamchapman

**Comment by hamchapman** [comment]
We've not got any work planned to add built-in support for this, but there's nothing stopping you from storing messages in your app.

**Comment by Tom-Fox1** [comment]
Ok, thanks for the quick reply. Btw I've loved using ChatKit so far - I was integrating with Twilio but just discovered Pusher and your documentation is far better and replacing their Chat SDK with yours has reduced the download size of my app by 12MB. Thanks for the great work!

**Comment by hamchapman** [comment]
Awesome - thanks for the kind words! 🙌
