### ISSUE TITLE
Would like ability to unsubscribe from a room

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-swift#132]
### What?

Would like the ability to unsubscribe from a room in swift/android and/or Node JS

Remaining subscribed to rooms when not in them significantly increases battery drain and also uses network bandwidth and CPU.  We need this to produce a consumer grade application using Chatkit.

### Environment

* **PusherChatkit version:**
* **Xcode version:**
* **Swift version:**
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by hamchapman** [comment]
This functionality is coming very soon to the Swift SDK: https://github.com/pusher/chatkit-swift/pull/130

It doesn't make sense in the context of the Node SDK though, as that doesn't support subscribing to a room.

**Comment by hamchapman** [comment]
Merged into master - will be in the next release, which will be going live today
