### ISSUE TITLE
Need to create PCAttachment to create a PCMessage with a link attachment

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-swift#134]
### What?

Please allow us to create attachments to pass into PCMessage.  Currently I create PCMessages which we use to create a virtual room before we actually create one. However, for attachments, I need the ability to create an attachment. Please update Attachment.swift to the following code so we can create attachments:

import Foundation
import PusherPlatform

public struct PCAttachment {
    public let link: String
    public let type: String
    public let name: String
    
    public init(link: String, type: String, name: String) {
        self.link = link
        self.type = type
        self.name = name
    }
}

### Environment

* **PusherChatkit version:**
* **Xcode version:**
* **Swift version:**
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by hamchapman** [comment]
You should be able to send a message with a link attachment using code like this:

```swift
currentUser.sendMessage(
    roomID: currentUser.rooms.last!.id,
    text: "A message with an attachment",
    attachment: .link("https://i.giphy.com/RpByGPT5VlZiE.gif", type: "image")
) { messageID, err in
    guard err == nil else {
        print("Error sending message \(err!.localizedDescription)")
        return
    }
}
```

**Comment by hitchingsh** [comment]
I think you misunderstand our requirement. It is to create a PCMessage with an attachment and your proposed solution does not support that.  

We have an application feature where we don't want the other users to see the messages until a certain time and because there is no official supported way to turn off notifications when doing sendMessage, we need to create virtual messages locally and thus are using PCMessage.

**Comment by hamchapman** [comment]
What do you then do with the virtual messages?

Also, `PCAttachment` is already public so you should already have access to it. Do you not?

**Comment by OliverPearmain-Pusher** [comment]
Its looks as if this feature request was addressed last year but the issue was never closed.
