### ISSUE TITLE
When a lot of messages (e.g. 10) are delivered at the same time, onMessage not called for all of them

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-swift#135]
### What?

When we send a lot of messages at once, onMessage is not called for all of them.  

### Environment

* **PusherChatkit version:**
1.2.3

* **Xcode version:**
* **Swift version:**

Swift 4.2

* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by hamchapman** [comment]
When you say delivered, do you also mean sent? If so, then it is likely the same underlying as #114

**Comment by hitchingsh** [comment]
When you deliver a fix for 114, I will test this and see if it also fixes this and if so I will close it out and let you know the results regardless.

**Comment by vivangkumar** [comment]
@hitchingsh This should have been resolved a while back. Apologies about not posting here. Are you still seeing this?

**Comment by vivangkumar** [comment]
Closing this issue. If it persists, please open a ticket with support@pusher.com.
