### ISSUE TITLE
Delegates don't provide basic information

### ISSUE THREAD

**Issue by jjatie** [pusher/chatkit-swift#138]
### What?
`PCRoomDelegate` names don't fit with traditional Cocoa (Touch) naming conventions. Additionally they don't provide all of the basic information supplied in Cocoa (Touch) delegates, particularly the caller. This requires strong references to be passed around and generate more potential scenarios for memory leaks.

An example:
```
protocol PCRoomDelegate: class {
    func onMessage(_ message: PCMessage)
}
```
should be at a minimum:
```
protocol PCRoomDelegate: class {
    func room(_ room: PCRoom, didRecieveMessage message: PCMessage)
}
```

but even better would be:
```
protocol PCRoomDelegate: class {
    func room(_ room: PCRoom, user: PCCurrentUser, didReceive message: PCMessage)
}
```

In the second and third examples we now get enough information passed in to easily update a local store (Core Data in my case) with room and message information.

A couple more preferred examples to fit with Cocoa Touch:
```
func room(_ room: PCRoom, userDidStartTyping user: PCUser)
func room(_ room: PCRoom, userDidStopTyping user: PCUser)
func room(_ room: PCRoom, userDidJoin user: PCUser)
func room(_ room: PCRoom, newCursor cursor: PCCursor)
```

### Environment

* **PusherChatkit version:** 1.2.3
* **Xcode version:** 10.1
* **Swift version:** 4.2
* **Platform(s) running PusherChatkit:** iOS 12.x

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by OliverPearmain-Pusher** [comment]
Suggestions are always appreciated, thank you.  However, I am going to close this issue because we are currently working on some significant updates to the Swift API and this feature request will be addressed in that update.
