### ISSUE TITLE
`setReadCursor` no longer working

### ISSUE THREAD

**Issue by jjatie** [pusher/chatkit-swift#144]
### What?
Using `setReadCursor` no longer works. Appears to be since Thursday, Feb 1. No code changes happened, but started getting errors in the completion handler of `setReadCursor` saying:
> [DEBUG] Unsupported API event name received: cursor_set

### Environment

* **PusherChatkit version:** 1.3.0
* **Xcode version:** 10.1
* **Swift version:** 4.2
* **Platform(s) running PusherChatkit:** iOS 12+

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by jjatie** [comment]
Seems to be fixed as of Friday, Feb 5

**Comment by jjatie** [comment]
Issue has reappeared. Testing as of `2019-02-06 00:47:53 +0000`

**Comment by populius** [comment]
same problem with [DEBUG] Unsupported API event name received: cursor_set

**Comment by ratulSharker** [comment]
I'm using following `PusherChatkit 1.4.1`, still getting this issue as follows

> [DEBUG] Unsupported API event name received: cursor_set

**Comment by mdpye** [comment]
Hi. The debug logging you quote is not an error - the event for new cursors changed in the past and currently both are sent with one being ignored as unrecognised. I've also checked the code, and we don't pass an error with test like that back to you in any completion handler, we only log it (at debug, not error or warn) and ignore the event.

If read cursors really have stopped working for you, please contact support@pusher.com, who can help you diagnose the problem.

I'm closing this issue, as nothing described here suggests read cursors actually aren't working. Again, if you have evidence other than the debug logging that they are not working, please contact support.
