### ISSUE TITLE
Room unread message count

### ISSUE THREAD

**Issue by clay-mindoula** [pusher/chatkit-swift#146]
### What?
I'm having a few issues trying to work out how to generate an "unread" message count correctly for a room. I get "my" (roomId) cursor position and then "their" cursor position (roomId, uid), calc is: their.position - my.position > 0. At the moment the only time "my" and "their" positions reconcile is when we are both in a room and we are in sync ie 0 unread. I am read-receipting all new messages but also read-receipting the last message loaded from history without actually checking current to see if it is necessary. So it is possible that unnecessary setReadCursor's are throwing off the room's position?

I also just noticed this error message from ChatKit:
Unsupported API event name received: cursor_set

Note: I hacked around this with a "vague" unread count "20+" and fishing around in the last 20 messages in a room? Can this be right?

thx!

### Environment

* **PusherChatkit version:** 1.3.0
* **Xcode version:** 10.1
* **Swift version:** 4.2.1
* **Platform(s) running PusherChatkit:** iOS (me) / Javascript (them)

### Demo Project (if you have one; it helps a lot!)

The following is the history for a room, the message id's are not incrementing sequentially as expected? 

▿ 4 elements
  ▿ 0 : MmrMessage
    - messageId : "4532767"
    ▿ sender : Sender
      - id : "Q-L7N66ikuKN132yAN6A"
      - displayName : "Q-L7N66ikuKN132yAN6A"
    ▿ sentDate : 2019-02-09 19:19:57 +0000
      - timeIntervalSinceReferenceDate : 571432797.0
    ▿ kind : MessageKind
      - text : "one"
    - message : "one"
    - checkinResults : nil
    - outGoing : nil
    - chatKitMessageState : Mindoula_Staging.ChatKitMessageState.completed
  ▿ 1 : MmrMessage
    - messageId : "4532769"
    ▿ sender : Sender
      - id : "Q-L7N66ikuKN132yAN6A"
      - displayName : "Q-L7N66ikuKN132yAN6A"
    ▿ sentDate : 2019-02-09 19:20:02 +0000
      - timeIntervalSinceReferenceDate : 571432802.0
    ▿ kind : MessageKind
      - text : "two"
    - message : "two"
    - checkinResults : nil
    - outGoing : nil
    - chatKitMessageState : Mindoula_Staging.ChatKitMessageState.completed
  ▿ 2 : MmrMessage
    - messageId : "4533070"
    ▿ sender : Sender
      - id : "Q-L7N66ikuKN132yAN6A"
      - displayName : "Q-L7N66ikuKN132yAN6A"
    ▿ sentDate : 2019-02-09 20:50:02 +0000
      - timeIntervalSinceReferenceDate : 571438202.0
    ▿ kind : MessageKind
      - text : "three"
    - message : "three"
    - checkinResults : nil
    - outGoing : nil
    - chatKitMessageState : Mindoula_Staging.ChatKitMessageState.completed
  ▿ 3 : MmrMessage
    - messageId : "4533075"
    ▿ sender : Sender
      - id : "Q-L7N66ikuKN132yAN6A"
      - displayName : "Q-L7N66ikuKN132yAN6A"
    ▿ sentDate : 2019-02-09 20:51:36 +0000
      - timeIntervalSinceReferenceDate : 571438296.0
    ▿ kind : MessageKind
      - text : "four"
    - message : "four"
    - checkinResults : nil
    - outGoing : nil
    - chatKitMessageState : Mindoula_Staging.ChatKitMessageState.completed

----

CC @hamchapman

**Comment by vivangkumar** [comment]
@clay-mindoula refer to this reply please: https://github.com/pusher/chatkit-client-js/issues/67#issuecomment-473964405.

Hopefully this will make it a lot easier to get unread counts for rooms!

**Comment by clay-mindoula** [comment]
I'm seeing the API documentation updated with unreadCount and lastMessageAt but
the swift api version 1.5.0 with those attributes on PCRoom isn't released?
ETA on this, its was 4/29?
