### ISSUE TITLE
Connect never returns

### ISSUE THREAD

**Issue by clay-mindoula** [pusher/chatkit-swift#147]
### What?
Connect fails and never returns. This has just started happening and is associated with ChatKit outputting the following in the debug window"

```Making attempt 2 of 6 in 1.0s. Error was: Bad response status code received: 401 with error message: services/chatkit_authorizer/authorization/room_membership_required: Room membership required``` 

As soon as I see this I know Connect is going to fail.

It does seem to be associated with a particular user. Any ideas on where I might look to try and investigate further?

### Environment

* **PusherChatkit version:**1.3.0
* **Xcode version:**10.1
* **Swift version:**4.2.1
* **Platform(s) running PusherChatkit:**iOS

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by benweitzman** [comment]
I'm seeing this issue too with chatkit 1.3

**Comment by saeedkargosha** [comment]
I'm seeing this issue too with chatkit 1.4.3

**Comment by saeedkargosha** [comment]
URLSession generalRequestURLSession became invalid
URLSession subscriptionURLSession became invalid
URLSession uploadURLSession became invalid
URLSession downloadURLSession became invalid

**Comment by vivangkumar** [comment]
@clay-mindoula sorry for the very late reply!

Are you seeing more logs? This should provide more information on which subscription is failing. The `connect` call is a number of subscriptions being made at the same time, so any one of those could've failed. However, I suspect it is either presence or cursors. Turning on `verbose` logging may help.

**Comment by clay-mindoula** [comment]
I have moved on, put it down to the general flakiness.

**Comment by OliverPearmain-Pusher** [comment]
Since this relates to an older version of the SDK and because we haven't heard anything further in some time I am going to close this issue. Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
