### ISSUE TITLE
onUserStoppedTyping not always called

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-swift#149]
### What?

public func onUserStoppedTyping(user: PCUser) {

not called for every call of:

public func onUserStartedTyping(user: PCUser) {

### Environment

* **PusherChatkit version:**

  - PusherChatkit (1.2.3):
    - BeamsChatkit (~> 1.2)
    - PusherPlatform (~> 0.6)
  - PusherPlatform (0.6.3)
  - PusherSwift (6.1.0):
    - CryptoSwift (~> 0.9.0)
    - ReachabilitySwift (~> 4.1.0)
    - Starscream (~> 3.0.5)

* **Xcode version:**

10.1

* **Swift version:**

4.2

* **Platform(s) running PusherChatkit:**

iOS

### Demo Project (if you have one; it helps a lot!)

----

**Comment by vivangkumar** [comment]
This should've also been fixed a while back. This was happening because of the same reason as #135.
