### ISSUE TITLE
Need asynchronous read cursor callback for client performance

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-swift#152]
### What?

We need asynchronous read cursor callback for client performance

```
self.currentUser.readCursor(id: roomId) { (PCCursor?, error) in
}
```

### Environment

* **PusherChatkit version:** 1.2.9
* **Xcode version:** 10.1
* **Swift version:** 4.2
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

**Comment by OliverPearmain-Pusher** [comment]
Suggestions are always appreciated, thank you.  However, I am going to close this issue because we are currently working on some significant updates to the Swift API and this feature request will either be addressed or will no longer be relevant.
