### ISSUE TITLE
'payload' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by populius** [pusher/chatkit-swift#162]
### What?
Get protection error from example docs

@hamchapman 
@vivangkumar

### Environment

* **PusherChatkit version:** 1.4.1
* **Xcode version:** 10.1
* **Swift version:** 4.2
* **Platform(s) running PusherChatkit:**

![Снимок экрана 2019-03-19 в 14 35 05](https://user-images.githubusercontent.com/2752484/54588026-5e38cd80-4a54-11e9-98a7-b71dbc67c93d.png)

**Comment by vivangkumar** [comment]
Uh oh! Thank you for reporting this @populius. I'll push out a fix soon!

**Comment by vivangkumar** [comment]
Hey @populius I've pushed a new version (1.4.2) that should resolve this and other such occurrences. Thank you once again for reporting this!
