### ISSUE TITLE
'url' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by caldrian** [pusher/chatkit-swift#164]
### What?

The sample code in the [reference](https://docs.pusher.com/chatkit/reference/swift#receiving-new-messages) cannot be compiled since `url` is inaccessible.

```
func onMultipartMessage(_ message: PCMultipartMessage) {
  for part in parts {
    switch part.payload {
      // other cases

      case .attachment(let payload):
        payload.url() { downloadURL, error in    <--- here
          // do something with the download url
        }
    }
  }
}
```

### Environment

* **PusherChatkit version: 1.4.2**
* **Xcode version: 10.1**
* **Swift version: 4.2**

----

**Comment by vivangkumar** [comment]
@caldrian new version incoming in the next half an hour. Thank you for bringing this up.
