### ISSUE TITLE
Cannot connect after updated backend API

### ISSUE THREAD

**Issue by olga-zhegulo** [pusher/chatkit-swift#168]
### What?
Chat cannot connect for a long time and crash finally.
User had logged by previous version of ChatKit (December 2018). After 18th March we replaced ChatKit beta version to current version at ChatKit server. Now old users cannot connect.
But new installation of client application connect successfully.
I suspect that old access token cause this issue.

### Environment

* **PusherChatkit version:**1.2.3
* **Xcode version:**10.0
* **Swift version:**4.2
* **Platform(s) running PusherChatkit:**
iOS (iPhone/iPad)
### Demo Project (if you have one; it helps a lot!)

----

**Comment by vivangkumar** [comment]
Hi!

Is it possible for you to paste error logs that you receive when you're trying to connect? Access tokens are refreshed if they're invalid.

**Comment by olga-zhegulo** [comment]
Sorry, we cannot provide log, we removed old instance of application we had. We had 401 error.
When I debugged, in fetchToken 'if' branch executed.

`
if let token = self.accessToken, let tokenExpiryTime = self.accessTokenExpiresAt {
            guard tokenExpiryTime > Date().timeIntervalSince1970 else {
                getTokenPair(completionHandler: retryAwareCompletionHandler)
                // TODO: Is returning here correct?
                return
            }
            completionHandler(PPTokenProviderResult.success(token: token))
        } else {
            getTokenPair(completionHandler: retryAwareCompletionHandler)
        }
`

**Comment by vivangkumar** [comment]
Is this still a recurring issue?

**Comment by olga-zhegulo** [comment]
We cannot check, because deleted instance with old tokens. 
We reproduced this issue several times yesterday.

**Comment by OliverPearmain-Pusher** [comment]
Since this relates to an older version of the SDK and because we haven't heard anything further in some time I am going to close this issue. Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
