### ISSUE TITLE
connect not happend

### ISSUE THREAD

**Issue by saeedkargosha** [pusher/chatkit-swift#171]
### Environment

* **PusherChatkit version:**1.4.4
* **Xcode version:**Version 10.1 (10B61)
* **Swift version:**4.2
* **Platform(s) running PusherChatkit:**iOS

let chatManager = ChatManager(
                instanceLocator: "v1:us1:52d114f3-25dd-40ca-bde3-4382b0f2dea2",
                tokenProvider: PCTokenProvider(url: "https://us1.pusherplatform.io/services/chatkit_token_provider/v1/52d114f3-25dd-40ca-bde3-4382b0f2dea2/token"),
                userID: "60",
                logger: TestLogger()
            )

            chatManager.connect(
                delegate: MyDelegate()
            ) { currentUser, error in
                guard error == nil else {
                    print("Error connecting: \(error!.localizedDescription)")
                    return
                }
                print("Connected!")
            }

TestLogger return : 
URLSession subscriptionURLSession became invalid
URLSession generalRequestURLSession became invalid
URLSession downloadURLSession became invalid
URLSession uploadURLSession became invalid

----

**Comment by cyurtbil** [comment]
Same here. And it receives the access token successfully and URL session succeeds while getting the token.

**Comment by cyurtbil** [comment]
I have asked this to Pusher support, they said I need to retain a strong reference to the ChatManager instance as mentioned on this page: [https://pusher.com/docs/chatkit/reference/swift#initialization](https://pusher.com/docs/chatkit/reference/swift#initialization). 

I was initializing and deallocating the chat manager instance in my ChatRoom controller. As soon as I initialized it only once when my app is launched (like a singleton), it worked.

**Comment by OliverPearmain-Pusher** [comment]
@cyurtbil point is completely valid.  Its essential that you hold a strong reference to your `ChatManager` instance.

Since we haven't heard anything further in some time I am going to close this issue.  Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.

**Comment by criscentreblue** [comment]
Hi @OliverPearmain-Pusher 
I'm getting this error when I call ChatManager.connect.
```
URLSession generalRequestURLSession became invalid
URLSession subscriptionURLSession became invalid
URLSession uploadURLSession became invalid
URLSession downloadURLSession became invalid
```

Environment
** PusherChatkit version:**1.8.3
**Xcode version:**11.3
**Swift version:**5.0
**Platform(s) running PusherPlatform:**iOS
