### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by jjatie** [pusher/chatkit-swift#176]
### What?
Using Carthage, building the frameworks take quite a bit of time, especially in something like CircleCI. While caching certainly alleviates the issue, [providing prebuilt frameworks](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) would eliminate it entirely.

**Comment by grzesiekko** [comment]
At the moment we are using Swift 4.2 to develop the framework. This stops us from providing prebuilt frameworks for Carthage. However, we might reconsider doing that once we upgrade to Swift 5.0 in future.
