### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by jjatie** [pusher/chatkit-swift#183]
### What?
Please include a Package.swift file to enable SPM support

**Comment by demosthese** [comment]
Any progress on this?

**Comment by grzesiekko** [comment]
This will be addressed in version 2.0 of Chatkit.

**Comment by OliverPearmain-Pusher** [comment]
Closing this because we are currently working on some significant updates to the Swift API and as @grzesiekko has mentioned this will include SPM support.
