### ISSUE TITLE
Add func onMultipartMessage(_ message: PCMultipartMessage) to PCChatManagerDelegate

### ISSUE THREAD

**Issue by clay-mindoula** [pusher/chatkit-swift#201]
### What?

chat master detail pages "always" have the last message for a room in the master page, avoid nasty proxy, multicast thingie.

### Environment

* **PusherChatkit version:**
* **Xcode version:**
* **Swift version:**
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

**Comment by OliverPearmain-Pusher** [comment]
Suggestions are always appreciated, thank you. However, I am going to close this issue because we are currently working on some significant updates to the Swift API and this feature request will likely either be addressed or will no longer be relevant.

**Comment by clay-mindoula** [comment]
any ETA on this? Very interested

**Comment by OliverPearmain-Pusher** [comment]
I'm afaid I cannot give you any indication of an ETA as we are still in the early stages of development and discovery.

If you would be interesting in working with us to help test early versions/prototypes of the updated SDK, at such a time that it is available, then please let us know.
