### ISSUE TITLE
PCChatManagerDelegate & PCRoomDelegate overlapping functions 

### ISSUE THREAD

**Issue by dustfire** [pusher/chatkit-swift#203]
### What?
`PCChatManagerDelegate` && `PCRoomDelegate` both have:

``` swift
    func onPresenceChanged(stateChange: PCPresenceStateChange, user: PCUser) {}
    func onNewReadCursor(_ cursor: PCCursor) {}
```
I see that you guys put these two methods on both Delegate protocols and also to made all these delegate methods optional by implementing empty functions for each:

``` swift
public protocol PCChatManagerDelegate: AnyObject {
    func onAddedToRoom(_ room: PCRoom)
    func onRemovedFromRoom(_ room: PCRoom)
....
}

public extension PCChatManagerDelegate {
    func onAddedToRoom(_ room: PCRoom) {}
    func onRemovedFromRoom(_ room: PCRoom) {}
....
}
```

However the issue is, if I have a Manager type of object which needs to serve as a delegate to both `PCChatManagerDelegate & PCRoomDelegate` then code won't compile due to redeclaration of two functions which are:

``` swift 
    func onPresenceChanged(stateChange: PCPresenceStateChange, user: PCUser) {}
    func onNewReadCursor(_ cursor: PCCursor) {}
```

Even worse, if I don't really just copy paste all the functions on both delegates in my extensions && comment out like below, the compiler error is just "you `ChatsManager does not conform to protocol PCRoomDelegate & PCChatManagerDelegate` -- as in not to much information as developer expects all functions to be optional yet somehow compiler is complaining... :

*** problematic ***
``` swift
extension ChatsManager: PCRoomDelegate {
  
    func onMultipartMessage(_ message: PCMultipartMessage) {
        print("Message received!")
    }
    
}

extension ChatsManager: PCChatManagerDelegate {

}

```

*** resolved ***
``` swift
extension ChatsManager: PCRoomDelegate {
    
    func onMultipartMessage(_ message: PCMultipartMessage) {
        print("Message received!")
    }
    func onMessage(_ message: PCMessage) {}
    func onMessageDeleted(_ messageID: Int) {}
    func onNewCursor(_ cursor: PCCursor) {}
    func onNewReadCursor(_ cursor: PCCursor) {}
    func onUserStartedTyping(user: PCUser) {}
    func onUserStoppedTyping(user: PCUser) {}
    func onUserJoined(user: PCUser) {}
    func onUserLeft(user: PCUser) {}
    func onPresenceChanged(stateChange: PCPresenceStateChange, user: PCUser) {}
    func onUsersUpdated() {}
    
}

extension ChatsManager: PCChatManagerDelegate {
    func onAddedToRoom(_ room: PCRoom) {}
    func onRemovedFromRoom(_ room: PCRoom) {}
    func onRoomUpdated(room: PCRoom) {}
    func onRoomDeleted(room: PCRoom) {}
    func onUserStartedTyping(inRoom: PCRoom, user: PCUser) {}
    func onUserStoppedTyping(inRoom: PCRoom, user: PCUser) {}
    func onUserJoinedRoom(_ room: PCRoom, user: PCUser) {}
    func onUserLeftRoom(_ room: PCRoom, user: PCUser) {}
//    func onPresenceChanged(stateChange: PCPresenceStateChange, user: PCUser) {}
//    func onNewReadCursor(_ cursor: PCCursor) {}
    func onError(error: Error) {}
}
```

It might help to rename these functions on one of the delegates so there are no redeclarations on function signatures to prevent further issues with other developers that use your SDKs. hope this helps. thank you guys awesome SDK regardless.

### Environment

* **PusherChatkit version:**
latest
* **Xcode version:**
latest
* **Swift version:**
latest
* **Platform(s) running PusherChatkit:**
iOS

### Demo Project (if you have one; it helps a lot!)
Nah

----

**Comment by OliverPearmain-Pusher** [comment]
Suggestions are always appreciated, thank you. However, I am going to close this issue because we are currently working on some significant updates to the Swift API and this feature request will no longer be relevant.
