### ISSUE TITLE
Crash on ChatManager.disablePushNotifications()

### ISSUE THREAD

**Issue by chickdan** [pusher/chatkit-swift#247]
### What?
After updating to SDK v 1.8.3 (from 1.8.2) our app is crashing when we call `ChatManager.disablePushNotifications()`. It looks like the source of the crash traces back to the `clearAllState(completion:)` function in `PushNotificationsStatic.swift` at line 136, resulting in the following error: `fatalError("PushNotifications.shared.start must have been called first")`. SDK v1.8.2 works as expected.

### Environment

* **PusherChatkit version:**
1.8.3
* **Xcode version:**
11.3 and 11.3.1
* **Swift version:**
5.0
* **Platform(s) running PusherChatkit:**
iOS

### Demo Project (if you have one; it helps a lot!)
Unfortunately don't have one, but our code follows the implementation guide for ChatKit.

----

**Comment by luismfonseca** [comment]
Please manually update your dependencies so that you have the push notifications version 3.0.4 which should fix this issue.

Closing it for now but let us know if there are any issues.
