### ISSUE TITLE
Crash on sendMultipartMessage (sending image) when going into background

### ISSUE THREAD

**Issue by jakubwarchol** [pusher/chatkit-swift#256]
### What?

Will update this with more info and stack trace later..

### Environment

* **PusherChatkit version:** 1.8.1
* **Xcode version:** 11.2.1
* **Swift version:** Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

**Comment by OliverPearmain-Pusher** [comment]
Since we haven't heard back withe additional info and stack trace promised I am going to close this issue. Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
