### ISSUE TITLE
Room unreadCount not filtering the unread messages just for current user

### ISSUE THREAD

**Issue by victormihaita** [pusher/chatkit-swift#274]
### What?
The unreadCount parameter on a room is returning the total unread messages (for all users in that room) instead on the unread messages for the currentUser only.

### Environment
* **PusherChatkit version: 1.8.3
* **Xcode version: 11.3.1
* **Swift version: 5
* **Platform(s) running PusherChatkit: iOS

**Comment by mdpye** [comment]
Hi @victormihaita 

Could we ask you to get in touch with support@pusher.com please. If possible, provide steps to reproduce or some samples from your testing showing the expected and actual output?

Thanks

**Comment by victormihaita** [comment]
I wrote an email. Thanks.

**Comment by grzesiekko** [comment]
This issue has been solved by support.
