### ISSUE TITLE
When is the Room's unreadCount changed?

### ISSUE THREAD

**Issue by roscoej** [pusher/chatkit-swift#281]
### What?
The unreadCount of Room object is not changed after loaded all messages for the room.
I also tried to set cursor for all messages but it didn't solve the problem.
When is the unreadCount value changed?

### Environment

* **PusherChatkit version: 1.8.3**
* **Xcode version: 11.3**
* **Swift version: 5**
* **Platform(s) running PusherChatkit: 0.7.2**

**Comment by benw-pusher** [comment]
Hello,

It is with great regret that we have to tell you that on April 23 2020 Pusher will be fully retiring our Chatkit product.

We started Chatkit 2 years ago and we want to thank all our partners, staff past and present, and customers who have joined us on this exciting journey.
 
This isn’t a decision that we’ve taken lightly and we know that it may cause significant challenges for our customers who have adopted Chatkit over the last 2 years. 

We’ve had to face the sad reality that despite the best efforts of our dedicated team it’s become increasingly difficult to establish Chatkit in a crowded and highly competitive market.

We have been searching for alternatives to this decision but in the current financial climate, hugely impacted by the recent COVID-19 pandemic, we have not been able to find a viable way for the Chatkit service to continue. 

So with no way forward for Chatkit we’ve had no choice but to begin the process of retiring the service. 

At this point I'd like to thank you for your support of Chatkit and apologise for the devastating decision we’ve had to make. 

In light of this news we must advise that you look to migrate from Chatkit by April 23 2020. You can read our migration advice on our [help center](https://support.pusher.com/hc/en-us/articles/360007009257).
