### ISSUE TITLE
Joining Rooms

### ISSUE THREAD

**Issue by nitrag** [pusher/chatkit-swift#58]
There is an error response when joining the same room twice (easy mistake if you are following the getting started guide).

```
[DEBUG] Maximum number of attempts (1) made. Latest error: Bad response status code received: 400 with error message: 
Error joining room: Maximum number of attempts made. The last error receieved was: Bad response status code received: 400 with error message:
```

Seems to me the server should succeed anyway (if already joined) and return the `Room` object anyway.

**Comment by hamchapman** [comment]
A fix for this has been merged into the server repo and as soon as the next deployment happens (should be soon!) this will no longer cause an error 👍  Thanks for the feedback!
