### ISSUE TITLE
How to handle push notification?

### ISSUE THREAD

**Issue by lukaspili** [pusher/chatkit-swift#63]
Hello,
Follow-up from #57 => What is the current way to handle push notifications with ChatKit?
Didn't find any mention of it in the docs.
Thanks.

**Comment by hot-leaf-juice** [comment]
Hi!

There's currently no explicit integration with push notifications, but we'll be releasing a version of the swift SDK with read cursors support _very soon_ (apparently this afternoon... 😉). When you have read cursors support, and depending on your precise requirements, something like the following might work:

- set messages as read as they come in
- keep track of sent messages and periodically check server side how far each user has read up to in each room ([read cursors api reference](https://docs.pusher.com/chatkit/reference/cursors))
- if a message has been sent but not read after a certain amount of time that you decide, send a push notification

**Comment by lukaspili** [comment]
Sounds great, this workflow would totally work for us 👍 .
Thank you for the quick answer.

**Comment by bookercodes** [comment]
If you want to add push notifications to your Chatkit app, you may find this helper useful: https://github.com/gildebrand/chatkit-push-helper!

**Comment by hamchapman** [comment]
It's still something we're interested in providing a solution for but we've not tackled it yet.

**Comment by gianpaj** [comment]
I want to chime in for a more seamless integration between Chatkit and Push Notifications (Beams or similar).

I have a fork of this repo running on my server https://github.com/gildebrand/chatkit-push-helper and it's not working anymore.
I need to put in time into debugging this, thankfully this is not affecting many users, but if we were serving thousands of customers, not having push notifications working for our chat would a blocker!

Having an in-app chat and having to manually poll Chatkit servers every time to know if messages have been read it's really bad.

Is there a way to signal how this important is to us, and I'm sure many more of your paying customers, and potential customers?
Who do we have to bribe? 😆

**Comment by teminer** [comment]
@jordaneharp would be a good person to start with ;)

**Comment by williamluke4** [comment]
Has there been any movement on this? @hamchapman
