### ISSUE TITLE
Project not building with PusherChatkit v.0.6.0

### ISSUE THREAD

**Issue by nyeu** [pusher/chatkit-swift#66]
### What?
Your SDK doesn't compile in my project.
I have installed your SDK through Cocoapods in my project and when I try to build it, it fails.
The error is in PCTokenProvider.swift, line 22:
```Instance member 'url' cannot be used on type 'PCTokenProvider'```

<img width="1135" alt="screen shot 2018-02-18 at 13 34 28" src="https://user-images.githubusercontent.com/7888779/36352417-931b4152-14b0-11e8-87fe-c0091344d349.png">

I am not sure if it's me missing something or I am not using the latest stable version.

### Environment

* **PusherChatkit version:** 0.6.0
* **Xcode version:** 9.2
* **Swift version:** 3.2
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

Thank you

----

CC @hamchapman

**Comment by hamchapman** [comment]
Hey @nyeu, sorry for the slow response!

I believe that error will be because you're using Swift 3.2. I think I've seen that error when using versions of Swift < 4. 

Are you restricted to using Swift 3.2 or would you be able to use 4.0+?

**Comment by hamchapman** [comment]
Closing as stale. Let me know if this is still a problem
