### ISSUE TITLE
Typing events broken after 0.7.0

### ISSUE THREAD

**Issue by steve228uk** [pusher/chatkit-swift#72]
### What?

A [change was made in v0.7.0](https://github.com/pusher/chatkit-swift/blob/f27fa3861c13ba197d9a1d376c099995ce256161/CHANGELOG.md#070---2018-03-26) to remove the `userSubscription` reference from the `ChatManager`. This change has now broken events such as `userStartedTyping` and `userStoppedTyping`.

The error that is now returned is `[ERROR] currentUser property not set on PCUserSubscription`. I'd submit a PR but I'm not sure where the reference to `PCUserSubscription` is in order to set the `currentUser` property

### Environment

* **PusherChatkit version:** 0.7.0
* **Xcode version:** 9.3
* **Swift version:** 4.1
* **Platform(s) running PusherChatkit:** iOS

----

CC @hamchapman

**Comment by hamchapman** [comment]
Weird! This should be being done here: https://github.com/pusher/chatkit-swift/blob/f27fa3861c13ba197d9a1d376c099995ce256161/Sources/ChatManager.swift#L102-L105

I'll have to investigate this some more on Monday. Thanks for the report!

**Comment by steve228uk** [comment]
@hamchapman Thanks for getting back to me, appreciate it. Have a great weekend 😊

**Comment by hamchapman** [comment]
I've now just released 0.7.2 which fixes this. I should have made it part of the 0.7.1 release, sorry!

Thanks for the report again though 👍
