### ISSUE TITLE
When calling PCCurrentUser.leaveRoom(id:completionHandler:) a crash occurs

### ISSUE THREAD

**Issue by steve228uk** [pusher/chatkit-swift#74]
### What?

When `PCCurrentUser.leaveRoom(id:completionHandler:)` is called it causes a recursive crash (see attached screenshot)

<img width="511" alt="screen shot 2018-04-12 at 21 49 53" src="https://user-images.githubusercontent.com/1169297/38703673-ce347dac-3e9b-11e8-91ae-af124c86408a.png">

### Environment

* **PusherChatkit version:** 0.7.0
* **Xcode version:** 9.3
* **Swift version:** 4.1
* **Platform(s) running PusherChatkit:** iOS + Simulator

----

CC @hamchapman

**Comment by steve228uk** [comment]
This seems to be caused by [two methods having the same signature](https://github.com/pusher/chatkit-swift/blob/9c249cc883c7bebe512454c31b4e33dc33761f89/Sources/PCCurrentUser.swift#L406-L423) which is causing the recursion and ultimately the crash.

The private method should likely be renamed.

**Comment by hamchapman** [comment]
Ah, good catch. I think it's even simpler than that: https://github.com/pusher/chatkit-swift/blob/9c249cc883c7bebe512454c31b4e33dc33761f89/Sources/PCCurrentUser.swift#L407

That function is directly calling itself. The first parameter should be `roomId`, not just `id`.

I'll push out a new version with that fix in it today.

**Comment by hamchapman** [comment]
Just released version 0.7.1 that fixes this, and includes the fix that was in #71 

Thanks for all the reports and PR @steve228uk !
