### ISSUE TITLE
Request: Make error handlers optional

### ISSUE THREAD

**Issue by steve228uk** [pusher/chatkit-swift#75]
### What?

For some calls to the ChatKit API it's unlikely an error handler will always be necessary. For example, I'm not particularly bother if the `stoppedTypingIn(_ room:)` method fails. 

As such it might be a nice improvement to make some of these handlers optional. 

### Environment

* **PusherChatkit version:** 0.7.0
* **Xcode version:** 9.3
* **Swift version:** 4.1
* **Platform(s) running PusherChatkit:** iOS

----

CC @hamchapman

**Comment by OliverPearmain-Pusher** [comment]
Suggestions are always appreciated, thank you.  However, I am going to close this issue because we are currently working on some significant updates to the Swift API and this feature request will no longer be relevant.
